package br.com.alura.jdbc.aula7;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class TestaExecute_DDL_DML {
	
	private static String queryDropTableProduto = "DROP TABLE PRODUTO";
	private static String queryCreateTableProduto = "CREATE TABLE Produto (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(255), descricao VARCHAR(255))";
	private static String queryInsertProduto1 = "INSERT INTO Produto VALUES (1,'Geladeira','Geladeira 2 portas')";
	private static String queryInsertProduto2 = "INSERT INTO Produto VALUES (2,'Ferro de passar','Ferro de passar roupa com vaporizador')";
	
	private static Connection getConnection() throws SQLException {
		Connection connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/loja-virtual", "SA", "");
		return connection;
	}
	
	public static void main(String[] args) throws SQLException {
		Connection connection = getConnection();
		System.out.println("--- Inicio Drop Table Produto ---");
		Statement statement = connection.createStatement();
		
		statement.execute(queryDropTableProduto);
		System.out.println("Deletado com sucesso");
		
		statement.execute(queryCreateTableProduto);
		System.out.println("Criado com sucesso");
		
		statement.execute(queryInsertProduto1);
		System.out.println("Produto 1 inserido com sucesso");
		
		statement.execute(queryInsertProduto2);
		System.out.println("Produto 2 inserido com sucesso");
	}
}
